### ISSUE TITLE
Invalid project

### ISSUE THREAD

**Issue by mayocaballero** [coma/msds#1]
Hi!

I selected the template from the plugin in Sketch (52.1), and a mesagge of error appeared :(

I attached the screenshot.

Thanks
![captura de pantalla 2018-10-11 a las 13 15 55](https://user-images.githubusercontent.com/13483146/46800480-1486e100-cd58-11e8-8577-af737afb9806.png)

**Comment by eduardo-syltek** [comment]
Hello @mayocaballero!

We'll be showing every validation error message in that red screen soon...

I can see that you hace two projects and one of them (the one titled with "New project") is pretty empty, there are no items under any of the required sections so rendering it on the Sketch plugin is impossible therefore the validation error appears.

Would you mind checking is by adding a color, a text color, a typography, a valid text style and trying to import it again?

❤️THANK YOU!!!

**Comment by coma** [comment]
Done!
