### ISSUE TITLE
Invalid project with full data on it

### ISSUE THREAD

**Issue by Bellver** [coma/msds#2]
Hi, I'm preparing a review with my experience using MSDS.
But for now I have a project that seems corrupt. 

I think the reason could be change almost everything after I configure my text styles. 
I change color and color groups name, text color and text color group name, delete a text style group...

After that fail attempt I replicate the work in other project doing all in one time in cascade and everything works well.

Here is the link of the project:  
https://ds.mendesaltaren.com/projects/4092c4cd-4f89-4df4-a816-d95f16b12a89

Congratulations for that amazing work guys! 
Pablo Bellver.

**Comment by eduardo-syltek** [comment]
Hi @Bellver!

Thank you for adding a link to the project, I'll take a look at it and tell you what is wrong with it.

The "red screen of dead" is pretty useless at the moment without the validation messages hidden behind it, it usually fails for things like empty sections or empty names...

**Comment by Bellver** [comment]
Hi Edu! 
_(Can I call you Edu?)_

**First_**  I'm looking for this "empty group under the color section", but I haven't got success yet.

I'm doing visual inspection helping me with the sections of the left sidebar, reading the .json and doing a inspection on chrome ... nothing. I'm sure it's a piece of cake fix it but I don't look the empty group anywhere! Can u send me a screeshot or similar feedback --> pablobellver.design@gmail.com 

**Second_** I'm ready for do all functional testing that team needs. If I can help at any point, I'll be delighted. Your plugin are helping my team to migrate all our libraries to the new workflow of sketch with style and text layers in a way I've not expected. 

**Third_** Relax a bit the validation rules and give more visual feedback it's a win for sure. It's one of my notes of the review i'm preparing. I'm searching some extra time for finish it and share it.

**Comment by coma** [comment]
@Bellver great feedback!

Yupe, we have relaxed the validation rules and added some messages to the Red Screen of Dead (tm) already, so check it out!

Can you share here the failing project? (donwload the json and paste it here).

**Comment by coma** [comment]
Ok @Bellver, I have news for you!

There is an empty letter spacing saved as null and being converted into NaN, so yupe, this is another bug and I'm on it right now.

I've also fixed you project.

Thank you!

**Comment by coma** [comment]
Now you'll have instant feedback on any validation issue within the item card. Try deleting a letter spacing from any text style and the whole card will turn red.
