### ISSUE TITLE
Subpixel letter-spacing

### ISSUE THREAD

**Issue by dennisamstein** [coma/msds#4]
Hola,
He notado que no acepta decimales en letter-spacing.
Esto es más bien un request… son aquí los request? no se mucho de Github.
saludos

**Comment by eduardo-syltek** [comment]
Cierto @dennisamstein, estoy validando que sean enteros pero podrían ser decimales perfectamente así que lo añado en la siguiente versión.

**Comment by coma** [comment]
Done!
