### ISSUE TITLE
Quick access to the project

### ISSUE THREAD

**Issue by Bellver** [coma/msds#5]
AS a designer
I NEED a quick access to the project i'm working from sketch
SO THAT speed my process eliminating the need of opening the browser and search the project. 

Sorry, is not a issue, is a new feature. 
 I have more than 5 projects and this new feature speed my process a lot. 

Maybe a link on the plugin menu, maybe a button on the sketch interface..

Thanks for your work!

**Comment by coma** [comment]
That's a good feature indeed! I'm adding it to our backlog.

**Comment by coma** [comment]
We'll be working on this as well.
