### ISSUE TITLE
Transparent colors for text

### ISSUE THREAD

**Issue by Bellver** [coma/msds#6]
**AS** a designer
**I NEED** opacity on colors
**SO THAT** makes me possible configure text colors for dark/light themes 

## Context
For text colors we used the material nomenclature: 
- High-emphasis: 100% Opacity
- Medium-emphasis: 60% Opacity
- Disabled: 38% Opacity

It's a cool way of configure the text colors because it allows the team configure with two text colors all the combinations for text taking into account accessibility. I think with this the MSDS will be more flexible too. 

NOW we import to sketch and change text style on sketch before start working. 

Sorry, is not a issue, is a new feature (again)
Thanks for your work!

**Comment by eduardo-syltek** [comment]
@Bellver, do you know that [every color format from CSS](https://www.w3schools.com/cssref/css_colors_legal.asp) is allowed right?

Maybe something like ```rgba(255, 0, 0, .5)``` can help here right now.

**Comment by coma** [comment]
@Bellver, we have been discussing this and decided to add it as a feature on or roadmap, like a section for layer styles.
