### ISSUE TITLE
Clone projects! 

### ISSUE THREAD

**Issue by Bellver** [coma/msds#7]
**AS** a designer
**I NEED** clone or copy a project from my account
**SO THAT** speed my process eliminating the need of start a project from scratch

# Context
When I start a project I repeat the most of color, text color and text style groups. 
We don't repeat typography because it change almost every time. 

**Our actual structure is something similar of this** 
... and we have to configure every time. -> OUR PAIN. We always want less work 😂

## COLOR
- Primary palette
-- Primary
-- Primary light
-- Primary dark
- Other palettes*
- Color palette
- ✒️ on LIGHT BG**
-- on LIGHT BG / High-emphasis
-- on LIGHT BG / Medium-emphasis
-- on LIGHT BG / Disabled
- ✒️ on DARK BG**
-- on DARK BG / High-emphasis
-- on LIGHT BG / Medium-emphasis
-- on LIGHT BG / Disabled
## TEXT COLOR
- on LIGHT BG
- on DARK BG
- Color palette
## TEXT STYLE
- Headers
-- H1 
-- H2 
-- H3
-- H4
-- H5
- Navitagation 
-- Buttons
-- Links
- Texts
-- Title
-- Subheader
-- Body
-- Caption
-- Small

**NOTE:** We use [color group] / [color name] to order properly the text styles. This configuration obligate us to eliminate the color group for the layer style on sketch. We love emoji on titles! 

_* We don't need to clone this group always. It depends if the product have secondary palette, the client company have more than a brand or if the product have specific palette. But I want to put there for explain our structure. 
** We use this color groups for the future text colors. New feature for this too #6_ 😙

Sorry, is not a issue, is a new feature (again)
Thanks for your work!

Thanks for your work!

**Comment by eduardo-syltek** [comment]
Cloning projects is a feature that might get into our roadmap, but for now you can download a base project and upload it to a new project every time.
